/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mikelangelo_osvprocessbuilder_OsvProcessBuilder */

#ifndef _Included_org_mikelangelo_osvprocessbuilder_OsvProcessBuilder
#define _Included_org_mikelangelo_osvprocessbuilder_OsvProcessBuilder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mikelangelo_osvprocessbuilder_OsvProcessBuilder
 * Method:    execve
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[JI)I
 */
JNIEXPORT jint JNICALL Java_org_mikelangelo_osvprocessbuilder_OsvProcessBuilder_execve
  (JNIEnv *, jobject, jstring, jobjectArray, jobjectArray, jlongArray, jint);

/*
 * Class:     org_mikelangelo_osvprocessbuilder_OsvProcessBuilder
 * Method:    waittid
 * Signature: (J[II)J
 */
JNIEXPORT jlong JNICALL Java_org_mikelangelo_osvprocessbuilder_OsvProcessBuilder_waittid
  (JNIEnv *, jclass, jlong, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
